qcacld-3.0: disable unused-but-set-variable warning
silence these warnings generated by Clang-14:

../drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_assoc.c:2213:28: error: variable 'psoc' set but not used [-Werror,-Wunused-but-set-variable]
        struct wlan_objmgr_psoc **psoc;
                                  ^
  CC      drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_sta_info.o
../drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_ioctl.c:2786:6: error: variable 'v' set but not used [-Werror,-Wunused-but-set-variable]
        int v = 0;
            ^
../drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_regulatory.c:666:41: error: variable 'wiphy_chan_144' set but not used [-Werror,-Wunused-but-set-variable]
        struct ieee80211_channel *wiphy_chan, *wiphy_chan_144 = NULL;
                                               ^
../drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_regulatory.c:668:10: error: variable 'band_capability' set but not used [-Werror,-Wunused-but-set-variable]
        uint8_t band_capability;
                ^
Signed-off-by: RaghuVarma331 <raghuvarma331@gmail.com>